FROM openjdk:8-jre

ENTRYPOINT ["/usr/local/openjdk-8/bin/java","-jar","/usr/local/javapkg/spring-boot-aws-beanstalk-0.0.1-SNAPSHOT.jar"]
ADD target/lib /usr/local/javapkg/lib/
ADD target/spring-boot-aws-beanstalk-0.0.1-SNAPSHOT.jar /usr/local/javapkg/spring-boot-aws-beanstalk-0.0.1-SNAPSHOT.jar

